package net.opentrends.training.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import net.opentrends.training.model.department;
import net.opentrends.training.service.departmentLocalServiceUtil;

/**
 * The extended model base implementation for the department service. Represents a row in the &quot;sample_department&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link departmentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see departmentImpl
 * @see net.opentrends.training.model.department
 * @generated
 */
public abstract class departmentBaseImpl extends departmentModelImpl
    implements department {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a department model instance should use the {@link department} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            departmentLocalServiceUtil.adddepartment(this);
        } else {
            departmentLocalServiceUtil.updatedepartment(this);
        }
    }
}
