package net.opentrends.training.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import net.opentrends.training.model.Department;
import net.opentrends.training.model.DepartmentModel;
import net.opentrends.training.model.DepartmentSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Department service. Represents a row in the &quot;sample_Department&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link net.opentrends.training.model.DepartmentModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DepartmentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DepartmentImpl
 * @see net.opentrends.training.model.Department
 * @see net.opentrends.training.model.DepartmentModel
 * @generated
 */
@JSON(strict = true)
public class DepartmentModelImpl extends BaseModelImpl<Department>
    implements DepartmentModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a department model instance should use the {@link net.opentrends.training.model.Department} interface instead.
     */
    public static final String TABLE_NAME = "sample_Department";
    public static final Object[][] TABLE_COLUMNS = {
            { "departmentid", Types.BIGINT },
            { "deptName", Types.VARCHAR }
        };
    public static final String TABLE_SQL_CREATE = "create table sample_Department (departmentid LONG not null primary key,deptName VARCHAR(75) null)";
    public static final String TABLE_SQL_DROP = "drop table sample_Department";
    public static final String ORDER_BY_JPQL = " ORDER BY department.departmentid ASC";
    public static final String ORDER_BY_SQL = " ORDER BY sample_Department.departmentid ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.net.opentrends.training.model.Department"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.net.opentrends.training.model.Department"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = false;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.net.opentrends.training.model.Department"));
    private static ClassLoader _classLoader = Department.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            Department.class
        };
    private long _departmentid;
    private String _deptName;
    private Department _escapedModel;

    public DepartmentModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static Department toModel(DepartmentSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        Department model = new DepartmentImpl();

        model.setDepartmentid(soapModel.getDepartmentid());
        model.setDeptName(soapModel.getDeptName());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<Department> toModels(DepartmentSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<Department> models = new ArrayList<Department>(soapModels.length);

        for (DepartmentSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public long getPrimaryKey() {
        return _departmentid;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setDepartmentid(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _departmentid;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return Department.class;
    }

    @Override
    public String getModelClassName() {
        return Department.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("departmentid", getDepartmentid());
        attributes.put("deptName", getDeptName());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long departmentid = (Long) attributes.get("departmentid");

        if (departmentid != null) {
            setDepartmentid(departmentid);
        }

        String deptName = (String) attributes.get("deptName");

        if (deptName != null) {
            setDeptName(deptName);
        }
    }

    @JSON
    @Override
    public long getDepartmentid() {
        return _departmentid;
    }

    @Override
    public void setDepartmentid(long departmentid) {
        _departmentid = departmentid;
    }

    @JSON
    @Override
    public String getDeptName() {
        if (_deptName == null) {
            return StringPool.BLANK;
        } else {
            return _deptName;
        }
    }

    @Override
    public void setDeptName(String deptName) {
        _deptName = deptName;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
            Department.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public Department toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (Department) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        DepartmentImpl departmentImpl = new DepartmentImpl();

        departmentImpl.setDepartmentid(getDepartmentid());
        departmentImpl.setDeptName(getDeptName());

        departmentImpl.resetOriginalValues();

        return departmentImpl;
    }

    @Override
    public int compareTo(Department department) {
        long primaryKey = department.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof Department)) {
            return false;
        }

        Department department = (Department) obj;

        long primaryKey = department.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
    }

    @Override
    public CacheModel<Department> toCacheModel() {
        DepartmentCacheModel departmentCacheModel = new DepartmentCacheModel();

        departmentCacheModel.departmentid = getDepartmentid();

        departmentCacheModel.deptName = getDeptName();

        String deptName = departmentCacheModel.deptName;

        if ((deptName != null) && (deptName.length() == 0)) {
            departmentCacheModel.deptName = null;
        }

        return departmentCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(5);

        sb.append("{departmentid=");
        sb.append(getDepartmentid());
        sb.append(", deptName=");
        sb.append(getDeptName());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(10);

        sb.append("<model><model-name>");
        sb.append("net.opentrends.training.model.Department");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>departmentid</column-name><column-value><![CDATA[");
        sb.append(getDepartmentid());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>deptName</column-name><column-value><![CDATA[");
        sb.append(getDeptName());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
