package net.opentrends.training.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import net.opentrends.training.model.Department;
import net.opentrends.training.service.DepartmentLocalServiceUtil;

/**
 * The extended model base implementation for the Department service. Represents a row in the &quot;sample_Department&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DepartmentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DepartmentImpl
 * @see net.opentrends.training.model.Department
 * @generated
 */
public abstract class DepartmentBaseImpl extends DepartmentModelImpl
    implements Department {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a department model instance should use the {@link Department} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            DepartmentLocalServiceUtil.addDepartment(this);
        } else {
            DepartmentLocalServiceUtil.updateDepartment(this);
        }
    }
}
