package net.opentrends.training.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import net.opentrends.training.model.Manager;
import net.opentrends.training.service.ManagerLocalServiceUtil;

/**
 * The extended model base implementation for the Manager service. Represents a row in the &quot;sample_Manager&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ManagerImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ManagerImpl
 * @see net.opentrends.training.model.Manager
 * @generated
 */
public abstract class ManagerBaseImpl extends ManagerModelImpl
    implements Manager {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a manager model instance should use the {@link Manager} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            ManagerLocalServiceUtil.addManager(this);
        } else {
            ManagerLocalServiceUtil.updateManager(this);
        }
    }
}
