package net.opentrends.training.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import net.opentrends.training.model.marks;
import net.opentrends.training.service.marksLocalServiceUtil;

/**
 * The extended model base implementation for the marks service. Represents a row in the &quot;sample_marks&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link marksImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see marksImpl
 * @see net.opentrends.training.model.marks
 * @generated
 */
public abstract class marksBaseImpl extends marksModelImpl implements marks {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a marks model instance should use the {@link marks} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            marksLocalServiceUtil.addmarks(this);
        } else {
            marksLocalServiceUtil.updatemarks(this);
        }
    }
}
