package net.opentrends.training.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import net.opentrends.training.model.marks;
import net.opentrends.training.model.marksModel;
import net.opentrends.training.model.marksSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the marks service. Represents a row in the &quot;sample_marks&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link net.opentrends.training.model.marksModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link marksImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see marksImpl
 * @see net.opentrends.training.model.marks
 * @see net.opentrends.training.model.marksModel
 * @generated
 */
@JSON(strict = true)
public class marksModelImpl extends BaseModelImpl<marks> implements marksModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a marks model instance should use the {@link net.opentrends.training.model.marks} interface instead.
     */
    public static final String TABLE_NAME = "sample_marks";
    public static final Object[][] TABLE_COLUMNS = {
            { "id_", Types.BIGINT },
            { "rollNo", Types.INTEGER },
            { "percentage", Types.INTEGER },
            { "userId", Types.BIGINT },
            { "groupId", Types.BIGINT }
        };
    public static final String TABLE_SQL_CREATE = "create table sample_marks (id_ LONG not null primary key,rollNo INTEGER,percentage INTEGER,userId LONG,groupId LONG)";
    public static final String TABLE_SQL_DROP = "drop table sample_marks";
    public static final String ORDER_BY_JPQL = " ORDER BY marks.id ASC";
    public static final String ORDER_BY_SQL = " ORDER BY sample_marks.id_ ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.net.opentrends.training.model.marks"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.net.opentrends.training.model.marks"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = false;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.net.opentrends.training.model.marks"));
    private static ClassLoader _classLoader = marks.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] { marks.class };
    private long _id;
    private int _rollNo;
    private int _percentage;
    private long _userId;
    private String _userUuid;
    private long _groupId;
    private marks _escapedModel;

    public marksModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static marks toModel(marksSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        marks model = new marksImpl();

        model.setId(soapModel.getId());
        model.setRollNo(soapModel.getRollNo());
        model.setPercentage(soapModel.getPercentage());
        model.setUserId(soapModel.getUserId());
        model.setGroupId(soapModel.getGroupId());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<marks> toModels(marksSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<marks> models = new ArrayList<marks>(soapModels.length);

        for (marksSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public long getPrimaryKey() {
        return _id;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _id;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return marks.class;
    }

    @Override
    public String getModelClassName() {
        return marks.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("id", getId());
        attributes.put("rollNo", getRollNo());
        attributes.put("percentage", getPercentage());
        attributes.put("userId", getUserId());
        attributes.put("groupId", getGroupId());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long id = (Long) attributes.get("id");

        if (id != null) {
            setId(id);
        }

        Integer rollNo = (Integer) attributes.get("rollNo");

        if (rollNo != null) {
            setRollNo(rollNo);
        }

        Integer percentage = (Integer) attributes.get("percentage");

        if (percentage != null) {
            setPercentage(percentage);
        }

        Long userId = (Long) attributes.get("userId");

        if (userId != null) {
            setUserId(userId);
        }

        Long groupId = (Long) attributes.get("groupId");

        if (groupId != null) {
            setGroupId(groupId);
        }
    }

    @JSON
    @Override
    public long getId() {
        return _id;
    }

    @Override
    public void setId(long id) {
        _id = id;
    }

    @JSON
    @Override
    public int getRollNo() {
        return _rollNo;
    }

    @Override
    public void setRollNo(int rollNo) {
        _rollNo = rollNo;
    }

    @JSON
    @Override
    public int getPercentage() {
        return _percentage;
    }

    @Override
    public void setPercentage(int percentage) {
        _percentage = percentage;
    }

    @JSON
    @Override
    public long getUserId() {
        return _userId;
    }

    @Override
    public void setUserId(long userId) {
        _userId = userId;
    }

    @Override
    public String getUserUuid() throws SystemException {
        return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
    }

    @Override
    public void setUserUuid(String userUuid) {
        _userUuid = userUuid;
    }

    @JSON
    @Override
    public long getGroupId() {
        return _groupId;
    }

    @Override
    public void setGroupId(long groupId) {
        _groupId = groupId;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
            marks.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public marks toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (marks) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        marksImpl marksImpl = new marksImpl();

        marksImpl.setId(getId());
        marksImpl.setRollNo(getRollNo());
        marksImpl.setPercentage(getPercentage());
        marksImpl.setUserId(getUserId());
        marksImpl.setGroupId(getGroupId());

        marksImpl.resetOriginalValues();

        return marksImpl;
    }

    @Override
    public int compareTo(marks marks) {
        long primaryKey = marks.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof marks)) {
            return false;
        }

        marks marks = (marks) obj;

        long primaryKey = marks.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
    }

    @Override
    public CacheModel<marks> toCacheModel() {
        marksCacheModel marksCacheModel = new marksCacheModel();

        marksCacheModel.id = getId();

        marksCacheModel.rollNo = getRollNo();

        marksCacheModel.percentage = getPercentage();

        marksCacheModel.userId = getUserId();

        marksCacheModel.groupId = getGroupId();

        return marksCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(11);

        sb.append("{id=");
        sb.append(getId());
        sb.append(", rollNo=");
        sb.append(getRollNo());
        sb.append(", percentage=");
        sb.append(getPercentage());
        sb.append(", userId=");
        sb.append(getUserId());
        sb.append(", groupId=");
        sb.append(getGroupId());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(19);

        sb.append("<model><model-name>");
        sb.append("net.opentrends.training.model.marks");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>id</column-name><column-value><![CDATA[");
        sb.append(getId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>rollNo</column-name><column-value><![CDATA[");
        sb.append(getRollNo());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>percentage</column-name><column-value><![CDATA[");
        sb.append(getPercentage());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userId</column-name><column-value><![CDATA[");
        sb.append(getUserId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>groupId</column-name><column-value><![CDATA[");
        sb.append(getGroupId());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
