package net.opentrends.training.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import net.opentrends.training.model.Marks;
import net.opentrends.training.service.MarksLocalServiceUtil;

/**
 * The extended model base implementation for the Marks service. Represents a row in the &quot;sample_Marks&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MarksImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MarksImpl
 * @see net.opentrends.training.model.Marks
 * @generated
 */
public abstract class MarksBaseImpl extends MarksModelImpl implements Marks {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a marks model instance should use the {@link Marks} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            MarksLocalServiceUtil.addMarks(this);
        } else {
            MarksLocalServiceUtil.updateMarks(this);
        }
    }
}
