package net.opentrends.training.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import net.opentrends.training.model.Marks;
import net.opentrends.training.model.MarksModel;
import net.opentrends.training.model.MarksSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Marks service. Represents a row in the &quot;sample_Marks&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link net.opentrends.training.model.MarksModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MarksImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MarksImpl
 * @see net.opentrends.training.model.Marks
 * @see net.opentrends.training.model.MarksModel
 * @generated
 */
@JSON(strict = true)
public class MarksModelImpl extends BaseModelImpl<Marks> implements MarksModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a marks model instance should use the {@link net.opentrends.training.model.Marks} interface instead.
     */
    public static final String TABLE_NAME = "sample_Marks";
    public static final Object[][] TABLE_COLUMNS = {
            { "marksid", Types.BIGINT },
            { "rollNo", Types.INTEGER },
            { "percentage", Types.INTEGER },
            { "userId", Types.BIGINT },
            { "groupId", Types.BIGINT }
        };
    public static final String TABLE_SQL_CREATE = "create table sample_Marks (marksid LONG not null primary key,rollNo INTEGER,percentage INTEGER,userId LONG,groupId LONG)";
    public static final String TABLE_SQL_DROP = "drop table sample_Marks";
    public static final String ORDER_BY_JPQL = " ORDER BY marks.marksid ASC";
    public static final String ORDER_BY_SQL = " ORDER BY sample_Marks.marksid ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.net.opentrends.training.model.Marks"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.net.opentrends.training.model.Marks"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = false;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.net.opentrends.training.model.Marks"));
    private static ClassLoader _classLoader = Marks.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] { Marks.class };
    private long _marksid;
    private int _rollNo;
    private int _percentage;
    private long _userId;
    private String _userUuid;
    private long _groupId;
    private Marks _escapedModel;

    public MarksModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static Marks toModel(MarksSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        Marks model = new MarksImpl();

        model.setMarksid(soapModel.getMarksid());
        model.setRollNo(soapModel.getRollNo());
        model.setPercentage(soapModel.getPercentage());
        model.setUserId(soapModel.getUserId());
        model.setGroupId(soapModel.getGroupId());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<Marks> toModels(MarksSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<Marks> models = new ArrayList<Marks>(soapModels.length);

        for (MarksSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public long getPrimaryKey() {
        return _marksid;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setMarksid(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _marksid;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return Marks.class;
    }

    @Override
    public String getModelClassName() {
        return Marks.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("marksid", getMarksid());
        attributes.put("rollNo", getRollNo());
        attributes.put("percentage", getPercentage());
        attributes.put("userId", getUserId());
        attributes.put("groupId", getGroupId());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long marksid = (Long) attributes.get("marksid");

        if (marksid != null) {
            setMarksid(marksid);
        }

        Integer rollNo = (Integer) attributes.get("rollNo");

        if (rollNo != null) {
            setRollNo(rollNo);
        }

        Integer percentage = (Integer) attributes.get("percentage");

        if (percentage != null) {
            setPercentage(percentage);
        }

        Long userId = (Long) attributes.get("userId");

        if (userId != null) {
            setUserId(userId);
        }

        Long groupId = (Long) attributes.get("groupId");

        if (groupId != null) {
            setGroupId(groupId);
        }
    }

    @JSON
    @Override
    public long getMarksid() {
        return _marksid;
    }

    @Override
    public void setMarksid(long marksid) {
        _marksid = marksid;
    }

    @JSON
    @Override
    public int getRollNo() {
        return _rollNo;
    }

    @Override
    public void setRollNo(int rollNo) {
        _rollNo = rollNo;
    }

    @JSON
    @Override
    public int getPercentage() {
        return _percentage;
    }

    @Override
    public void setPercentage(int percentage) {
        _percentage = percentage;
    }

    @JSON
    @Override
    public long getUserId() {
        return _userId;
    }

    @Override
    public void setUserId(long userId) {
        _userId = userId;
    }

    @Override
    public String getUserUuid() throws SystemException {
        return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
    }

    @Override
    public void setUserUuid(String userUuid) {
        _userUuid = userUuid;
    }

    @JSON
    @Override
    public long getGroupId() {
        return _groupId;
    }

    @Override
    public void setGroupId(long groupId) {
        _groupId = groupId;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
            Marks.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public Marks toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (Marks) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        MarksImpl marksImpl = new MarksImpl();

        marksImpl.setMarksid(getMarksid());
        marksImpl.setRollNo(getRollNo());
        marksImpl.setPercentage(getPercentage());
        marksImpl.setUserId(getUserId());
        marksImpl.setGroupId(getGroupId());

        marksImpl.resetOriginalValues();

        return marksImpl;
    }

    @Override
    public int compareTo(Marks marks) {
        long primaryKey = marks.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof Marks)) {
            return false;
        }

        Marks marks = (Marks) obj;

        long primaryKey = marks.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
    }

    @Override
    public CacheModel<Marks> toCacheModel() {
        MarksCacheModel marksCacheModel = new MarksCacheModel();

        marksCacheModel.marksid = getMarksid();

        marksCacheModel.rollNo = getRollNo();

        marksCacheModel.percentage = getPercentage();

        marksCacheModel.userId = getUserId();

        marksCacheModel.groupId = getGroupId();

        return marksCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(11);

        sb.append("{marksid=");
        sb.append(getMarksid());
        sb.append(", rollNo=");
        sb.append(getRollNo());
        sb.append(", percentage=");
        sb.append(getPercentage());
        sb.append(", userId=");
        sb.append(getUserId());
        sb.append(", groupId=");
        sb.append(getGroupId());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(19);

        sb.append("<model><model-name>");
        sb.append("net.opentrends.training.model.Marks");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>marksid</column-name><column-value><![CDATA[");
        sb.append(getMarksid());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>rollNo</column-name><column-value><![CDATA[");
        sb.append(getRollNo());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>percentage</column-name><column-value><![CDATA[");
        sb.append(getPercentage());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userId</column-name><column-value><![CDATA[");
        sb.append(getUserId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>groupId</column-name><column-value><![CDATA[");
        sb.append(getGroupId());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
