package net.opentrends.training.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import net.opentrends.training.model.student;
import net.opentrends.training.service.studentLocalServiceUtil;

/**
 * The extended model base implementation for the student service. Represents a row in the &quot;sample_student&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link studentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see studentImpl
 * @see net.opentrends.training.model.student
 * @generated
 */
public abstract class studentBaseImpl extends studentModelImpl
    implements student {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a student model instance should use the {@link student} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            studentLocalServiceUtil.addstudent(this);
        } else {
            studentLocalServiceUtil.updatestudent(this);
        }
    }
}
