package net.opentrends.training.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Department service. Represents a row in the &quot;sample_Department&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link net.opentrends.training.model.impl.DepartmentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link net.opentrends.training.model.impl.DepartmentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Department
 * @see net.opentrends.training.model.impl.DepartmentImpl
 * @see net.opentrends.training.model.impl.DepartmentModelImpl
 * @generated
 */
public interface DepartmentModel extends BaseModel<Department> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a department model instance should use the {@link Department} interface instead.
     */

    /**
     * Returns the primary key of this department.
     *
     * @return the primary key of this department
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this department.
     *
     * @param primaryKey the primary key of this department
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the departmentid of this department.
     *
     * @return the departmentid of this department
     */
    public long getDepartmentid();

    /**
     * Sets the departmentid of this department.
     *
     * @param departmentid the departmentid of this department
     */
    public void setDepartmentid(long departmentid);

    /**
     * Returns the dept name of this department.
     *
     * @return the dept name of this department
     */
    @AutoEscape
    public String getDeptName();

    /**
     * Sets the dept name of this department.
     *
     * @param deptName the dept name of this department
     */
    public void setDeptName(String deptName);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(net.opentrends.training.model.Department department);

    @Override
    public int hashCode();

    @Override
    public CacheModel<net.opentrends.training.model.Department> toCacheModel();

    @Override
    public net.opentrends.training.model.Department toEscapedModel();

    @Override
    public net.opentrends.training.model.Department toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
