package net.opentrends.training.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Student1 service. Represents a row in the &quot;sample_Student1&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link net.opentrends.training.model.impl.Student1ModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link net.opentrends.training.model.impl.Student1Impl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Student1
 * @see net.opentrends.training.model.impl.Student1Impl
 * @see net.opentrends.training.model.impl.Student1ModelImpl
 * @generated
 */
public interface Student1Model extends BaseModel<Student1> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a student1 model instance should use the {@link Student1} interface instead.
     */

    /**
     * Returns the primary key of this student1.
     *
     * @return the primary key of this student1
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this student1.
     *
     * @param primaryKey the primary key of this student1
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the studentid of this student1.
     *
     * @return the studentid of this student1
     */
    public long getStudentid();

    /**
     * Sets the studentid of this student1.
     *
     * @param studentid the studentid of this student1
     */
    public void setStudentid(long studentid);

    /**
     * Returns the fname of this student1.
     *
     * @return the fname of this student1
     */
    @AutoEscape
    public String getFname();

    /**
     * Sets the fname of this student1.
     *
     * @param fname the fname of this student1
     */
    public void setFname(String fname);

    /**
     * Returns the lname of this student1.
     *
     * @return the lname of this student1
     */
    @AutoEscape
    public String getLname();

    /**
     * Sets the lname of this student1.
     *
     * @param lname the lname of this student1
     */
    public void setLname(String lname);

    /**
     * Returns the age of this student1.
     *
     * @return the age of this student1
     */
    public int getAge();

    /**
     * Sets the age of this student1.
     *
     * @param age the age of this student1
     */
    public void setAge(int age);

    /**
     * Returns the branch of this student1.
     *
     * @return the branch of this student1
     */
    @AutoEscape
    public String getBranch();

    /**
     * Sets the branch of this student1.
     *
     * @param branch the branch of this student1
     */
    public void setBranch(String branch);

    /**
     * Returns the email of this student1.
     *
     * @return the email of this student1
     */
    @AutoEscape
    public String getEmail();

    /**
     * Sets the email of this student1.
     *
     * @param email the email of this student1
     */
    public void setEmail(String email);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(net.opentrends.training.model.Student1 student1);

    @Override
    public int hashCode();

    @Override
    public CacheModel<net.opentrends.training.model.Student1> toCacheModel();

    @Override
    public net.opentrends.training.model.Student1 toEscapedModel();

    @Override
    public net.opentrends.training.model.Student1 toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
